# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
modmenu_version=18.0.0
cloth_config_version=26.1.154

# Mod Properties
version=26.1.2
group=com.awakey.nonametag

# Dependencies
fabric_api_version=0.155.3+26.1.2